- name: Patch
  shell: >
    docker exec geoprism bash -c '
      java $JAVA_OPTS -cp "$CATALINA_HOME/webapps/{{item}}/WEB-INF/classes:$CATALINA_HOME/webapps/{{item}}/WEB-INF/lib/*" net.geoprism.build.GeoprismDatabaseBuilder $CATALINA_HOME/webapps/{{item}}/WEB-INF/classes/metadata --rootUser={{rootdb_user}} --rootPass={{rootdb_pass}} --templateDb=postgres --install={{clean_db}} --clean={{clean_db}} 2>&1 | tee $CATALINA_HOME/logs/database-builder-{{item}}.log
      '
  with_items: 
    - "{{ apps | default([]) }}"
  become: yes
  become_method: sudo
  when: "apps is defined and not {{debug | default('false')}}"
  
- name: Patch (debug)
  shell: >
    docker exec geoprism bash -c '
      java $JAVA_OPTS_NO_DEBUG -cp "$CATALINA_HOME/webapps/{{item}}/WEB-INF/classes:$CATALINA_HOME/webapps/{{item}}/WEB-INF/lib/*" net.geoprism.build.GeoprismDatabaseBuilder $CATALINA_HOME/webapps/{{item}}/WEB-INF/classes/metadata --rootUser={{rootdb_user}} --rootPass={{rootdb_pass}} --templateDb=postgres --install={{clean_db}} --clean={{clean_db}} 2>&1 | tee $CATALINA_HOME/logs/database-builder-{{item}}.log
      '
  with_items: 
    - "{{ apps | default([]) }}"
  become: yes
  become_method: sudo
  when: "apps is defined and {{debug | default('false')}}"
  
- name: Boot
  shell: docker restart geoprism
  become: yes
  become_method: sudo