
- name: Kill OrientDB
  docker_container:
    name: orientdb
    state: absent
    force_kill: yes
    keep_volumes: no
  become: yes
  become_method: sudo
  when: "{{clean_orientdb}}"

- name: Delete Data
  file:
    state: absent
    path: /docker/volumes/orientdb
  become: yes
  become_method: sudo
  when: "{{clean_orientdb}}"

- name: Start OrientDB
  docker_container:
    name: orientdb
    image: "{{ orientdb_image | default('orientdb:3.0.25') }}"
    state: started
    recreate: true
    pull: true
    env:
      ORIENTDB_ROOT_PASSWORD: "{{orientdb_root_pass}}"
    exposed_ports:
      - 2424
      - 2480
    ports:
      - "{{ orientdb_port | default('2424') }}:2424"
      - "{{ orientdb_admin_port | default('2480') }}:2480"
    volumes:
      - /docker/volumes/orientdb/databases:/orientdb/databases
      - /docker/volumes/orientdb/backup:/orientdb/backup
    restart_policy: always
  become: yes
  become_method: sudo
  when: "{{clean_orientdb}}"
  
# When we're recreating the docker image for some reason docker leaves the old volume just sitting around unused. This was causing us to run out of space after x number of deploys
# https://lebkowski.name/docker-volumes/
- name: Clean dangling docker volumes
  shell: "docker volume rm $(docker volume ls -qf dangling=true)"
  become: yes
  become_method: sudo
  when: "{{clean_orientdb}}"
  ignore_errors: yes


# - name: Open port 5432 on iptables
#   iptables: 
# iptables -A INPUT -p tcp --dport 2195 -j ACCEPT
# service iptables restart