
# This is used to deploy an extension project of Geoprism
  
- name: Stage appcfg
  copy: src="{{appcfg}}/"
        dest="/tmp/staging/appcfg/"
  become: yes
  become_method: sudo
  when: appcfg is defined
- name: Deploy appcfg to Docker
  shell: "{{item}}"
  with_items:
    - docker exec geoprism bash -c 'rm -f $CATALINA_HOME/appcfg'
    - docker cp /tmp/staging/appcfg/ geoprism:"{{catalina_home}}/appcfg"
  become: yes
  become_method: sudo
  when: appcfg is defined
  
- name: Make Wars directory
  shell: "docker exec geoprism bash -c 'mkdir -p $CATALINA_HOME/wars'"
  become: yes
  become_method: sudo

- name: Download Artifact (public)
  shell: docker exec geoprism bash -c 'wget -nv -O $CATALINA_HOME/wars/geoprism.war "http://nexus.terraframe.com/service/local/artifact/maven/redirect?r=allrepos&g={{artifact_groupId}}&a={{artifact_id}}&p=war&v={{artifact_version}}"'
  become: yes
  become_method: sudo
  when: nexus_password is not defined

- name: Download Artifact (private)
  shell: docker exec geoprism bash -c 'wget --user={{nexus_user}} --password={{nexus_password}} -nv -O $CATALINA_HOME/wars/geoprism.war "http://nexus.terraframe.com/service/local/artifact/maven/redirect?r=private&g={{artifact_groupId}}&a={{artifact_id}}&p=war&v={{artifact_version}}"'
  become: yes
  become_method: sudo
  when: nexus_password is defined
  
- name: Extract Artifact
  shell: docker exec geoprism bash -c 'mkdir -p $CATALINA_HOME/wars/geoprism && cd $CATALINA_HOME/wars/geoprism && $JAVA_HOME/bin/jar xvf $CATALINA_HOME/wars/geoprism.war'
  become: yes
  become_method: sudo


## Configure log4j.properties ##
- name: Make webapp-replace directory
  shell: "mkdir -p /tmp/staging/webapp-replace"
  become: yes
  become_method: sudo
- name: Stage log4j.properties
  copy: src="../envcfg/webapp-replace/log4j2.properties"
        dest="/tmp/staging/webapp-replace/log4j2.properties"
  become: yes
  become_method: sudo
- name: Deploy log4j.properties to Docker
  shell: "{{item}}"
  with_items:
    - sed -i -e "s/rootLogger.level=error/rootLogger.level={{log_level | default("error")}}/g" /tmp/staging/webapp-replace/log4j2.properties
    - docker exec geoprism bash -c 'rm -f $CATALINA_HOME/wars/geoprism/WEB-INF/classes/log4j2.properties'
    - docker cp /tmp/staging/webapp-replace/log4j2.properties geoprism:"{{catalina_home}}/wars/geoprism/WEB-INF/classes/log4j2.properties"
  become: yes
  become_method: sudo
  
  
- name: Download & deploy geoserver
  shell: "{{item}}"
  with_items:
    - docker exec geoprism bash -c 'wget -nv -O $CATALINA_HOME/wars/geoserver.war "http://nexus.terraframe.com/service/local/repositories/releases/content/org/geoserver/geoserver/2.14.2/geoserver-2.14.2.war"'
    - docker exec geoprism bash -c 'mkdir -p $CATALINA_HOME/webapps/geoserver && cd $CATALINA_HOME/webapps/geoserver && $JAVA_HOME/bin/jar xvf $CATALINA_HOME/wars/geoserver.war'
  become: yes
  become_method: sudo

- name: Deploy Artifact
  shell: docker exec geoprism bash -c 'mv $CATALINA_HOME/wars/geoprism $CATALINA_HOME/webapps/ROOT'
  become: yes
  become_method: sudo
