
- name: Delete Data
  file:
    state: absent
    path: /docker/volumes/solr/configsets
  become: yes
  become_method: sudo
  when: "{{clean_solr | default(false)}}"
- name: Solr Make Configsets Dir
  file:
    state: directory
    path: /docker/volumes/solr/configsets
  become: yes
  become_method: sudo
  when: "{{clean_solr | default(false)}}"
  
- name: Copy Solr Config
  copy: src="{{solr_core_path}}/"
        dest="/docker/volumes/solr/configsets/"
  become: yes
  become_method: sudo
  when: "{{solr_enabled | default(false)}}"

# Solr Docker container
- name: Kill Solr
  shell: docker kill solr
  become: yes
  become_method: sudo
  ignore_errors: yes
  when: "{{solr_enabled | default(false)}} and {{clean_solr | default(false)}}"
- name: Start Solr
  docker_container:
    name: solr
    image: solr:6.6
    state: started
    recreate: "{{clean_solr}}"
    pull: yes
    restart_policy: always
    network_mode: host
    command: "solr-precreate {{solr_core_name}} {{solr_server}}/solr/configsets/{{solr_core_name}}"
    volumes:
      - "/docker/volumes/solr/{{solr_core_name}}:{{solr_server}}/solr/configsets/{{solr_core_name}}"
  become: yes
  become_method: sudo
  when: "{{solr_enabled | default(false)}} and {{clean_solr | default(false)}}"

# Third party libs
- name: Install libgdal
  shell: docker exec geoprism bash -c 'apt-get update && apt-get -y install libgdal-java'
  become: yes
  become_method: sudo
  when: "{{solr_enabled | default(false)}} and {{clean_solr | default(false)}}"

- name: Deploy Solr JTS
  shell: '{{item}}'
  with_items:
  # Install JTS into solr/server
    - docker cp /docker/volumes/solr/server 'solr:{{solr_server}}/../staging'
    - docker exec -u root solr bash -c 'cp -rf {{solr_server}}/../staging/* {{solr_server}}'
    - docker exec -u root solr bash -c 'rm -rf {{solr_server}}/../staging'
  when: "{{solr_enabled | default(false)}} and {{solr_jts | default(false)}}"
  become: yes
  become_method: sudo
- name: Restart Solr
  shell: "{{item}}"
  with_items:
    - docker stop solr
    - docker start solr
  become: yes
  become_method: sudo
  when: "{{solr_enabled | default(false)}}"
  
- name: Wait for Solr to be up
  wait_for: host="127.0.0.1" port=8983 delay=5 timeout=60 state=started
  when: "{{solr_enabled | default(false)}}"
  