
# Solr Docker container
- name: Kill Solr
  shell: docker kill solr
  become: yes
  become_method: sudo
  when: "{{clean_solr}}"
  ignore_errors: yes
- name: Start Solr
  docker_container:
    name: solr
    image: solr:6.6.5
    state: started
    recreate: "{{clean_solr}}"
    pull: yes
    restart_policy: always
    network_mode: host
  become: yes
  become_method: sudo

# Third party libs
- name: Install libgdal
  shell: docker exec geoprism bash -c 'apt-get update && apt-get -y install libgdal-java'
  become: yes
  become_method: sudo

# Deploy Solr Core
- name: Delete Solr Config staging
  file:
    state: absent
    path: "/tmp/staging/solr/"
- name: Stage Solr Config
  copy: src="{{solr_core_path}}/"
        dest="/tmp/staging/solr/"
- name: Does the solr core exist?
  stat:
    path: "{{solr_server}}/solr/{{solr_core_name}}"
  register: solr_core_exists
  become: yes
  become_method: sudo
- name: Create Solr Core
  shell: '{{item}}'
  with_items:
    - docker exec solr bash -c '/opt/solr/bin/solr create_core -c {{solr_core_name}}'
  become: yes
  become_method: sudo
  when: "{{clean_solr}}"
#  when: "not solr_core_exists.stat.exists or {{clean_solr}}"
- name: Deploy Solr JTS
  shell: '{{item}}'
  with_items:
  # Install JTS into solr/server
    - docker cp /tmp/staging/solr/server 'solr:{{solr_server}}/../staging'
    - docker exec -u root solr bash -c 'cp -rf {{solr_server}}/../staging/* {{solr_server}}'
    - docker exec -u root solr bash -c 'rm -rf {{solr_server}}/../staging'
  when: "{{solr_jts}}"
  become: yes
  become_method: sudo
- name: Deploy Solr Core Config
  shell: '{{item}}'
  with_items:
    - docker cp '/tmp/staging/solr/{{solr_core_name}}' 'solr:{{solr_server}}/solr/staging'
    - docker exec -u root solr bash -c 'cp -rf {{solr_server}}/solr/staging/* {{solr_server}}/solr/{{solr_core_name}}'
    - docker exec -u root solr bash -c 'rm -rf {{solr_server}}/solr/staging'
    - docker exec -u root solr bash -c 'chown -R solr:solr {{solr_server}}/solr/{{solr_core_name}}'
  become: yes
  become_method: sudo
- name: Restart Solr
  shell: "{{item}}"
  with_items:
    - docker stop solr
    - docker start solr
  become: yes
  become_method: sudo
  
- name: Wait for Solr to be up
  wait_for: host="127.0.0.1" port=8983 delay=5 timeout=60 state=started
  